name: Build Calculator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_calculator:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install PyInstaller
      run: |
        python -m pip install pyinstaller

    - name: Verify PyInstaller Installation
      run: |
        pyinstaller --version

    - name: Print Python Version
      run: |
        python --version

    - name: List Installed Packages
      run: |
        pip list

    - name: Build Calculator
      run: |
        python -m pyinstaller --onefile calculator.py
        mv dist/calculator ./calculator.exe
